version: "3"

services:
  authelia:
    container_name: authelia
    hostname: authelia.local
    image: docker.io/authelia/authelia:4
    env_file: .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
        TZ: Europe/Copenhagen
        PUID: 1000
        PGID: 1000
    volumes:
      - ./config:/config:rw
    networks:
      - proxy
    ports:
      - 9091:9091
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.authelia.rule=Host(`auth.l.wraaath.com`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.l.wraaath.com'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'

networks:
  proxy:
    external: true
